# Edit processing configuration here
source_data: source_data                # path to folder for holding downloads
temp_data: temp_data                    # path to folder for temp .gdb files
source_csv: sources.csv                 # file containing list of source layers
tolerance: 7                            # integrate tolerance (m)
grid: tiles_20k                         # alias of tile layer in datalist
tile_column: map_tile                   # tile name field in tile layer
# full path to output gdb *and* feature class
output: C:\projects\roadintegrator\integrated_roads.gdb\integrated_roads
# postgresql db SQLAlchemy connection string
db_url: postgresql://postgres:postgres@localhost:5432/roadintegrator
