# Edit processing configuration here
datalist: sources.csv                   # file containing list of source layers
grid: tiles_20k                         # alias of tile layer in datalist
tile_column: MAP_TILE                   # tile name field in tile layer
tolerance: 7                            # integrate tolerance (m)
output: integrated_roads                # output feature class name
