# -----------------
# input definitions
# -----------------
datalist: road_inputs.csv               # file containing list of source layers
tilelist: tiles.csv                     # file containing list of tiles to process (250k tiles)
grid: WHSE_BASEMAPPING.BCGS_20K_GRID    # BCGW tile layer to cut source / processing

# -----------------
# output feature classes and files
# -----------------

# -----------------
# path lookups
# Define path shortcuts used in datalist.csv other than $BCGW and $TMP here
# for example:
# $DSSWHSE: Q:\\dsswhse
# -----------------

# -----------------
# misc config settings
# -----------------
processes: 8                             # how many cores to use
tmpdir: roadintegrator                   # folder to create and write to on T

# -----------------
# if your BCGW user name is different from your IDIR name, set here (and uncomment)
# -----------------
# BCGW_USR: username