services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: ce_integratedroads-db
    command: postgres -c default_statistics_target=100 -c max_connections=20 -c max_locks_per_transaction=64 -c checkpoint_timeout=30min -c maintenance_work_mem=1GB -c effective_cache_size=16GB -c work_mem=500MB -c max_wal_size=10GB -c wal_buffers=16MB -c shared_buffers=8GB
    shm_size: 16gb
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 1s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PG_DATABASE=postgres
  runner:
    build:
      context: .
      dockerfile: docker/runner/Dockerfile
    container_name: ce_integratedroads-runner
    volumes:
      - "./:/home/ce_integratedroads"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_S3_ENDPOINT=${AWS_S3_ENDPOINT}
      - BUCKET=${BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_VIRTUAL_HOSTING=${AWS_VIRTUAL_HOSTING}
      - AWS_EC2_METADATA_DISABLED=${AWS_EC2_METADATA_DISABLED}
      - AWS_REQUEST_CHECKSUM_CALCULATION=when_required
      - AWS_RESPONSE_CHECKSUM_VALIDATION=when_required
      - CPL_VSISTDIN_BUFFER_LIMIT=${CPL_VSISTDIN_BUFFER_LIMIT}
      - DRAPWD=${DRAPWD}
    depends_on:
      db:
        condition: service_healthy

