version: "3.9"  
services:
  db:
    image: postgis/postgis:16-master
    container_name: ce_integratedroads
    ports:
      - 8001:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 1s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PG_DATABASE=ce_integratedroads
  app:
    build: .
    container_name: ce_integratedroads-client
    volumes:
      - "./:/home/ce_integratedroads"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ce_integratedroads
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - AWS_S3_ENDPOINT=${AWS_S3_ENDPOINT}
      - OBJECTSTORE_BUCKET=${OBJECTSTORE_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_VIRTUAL_HOSTING=${AWS_VIRTUAL_HOSTING}
      - AWS_EC2_METADATA_DISABLED=${AWS_EC2_METADATA_DISABLED}
      - CPL_VSISTDIN_BUFFER_LIMIT=${CPL_VSISTDIN_BUFFER_LIMIT}
    depends_on:
      db:
        condition: service_healthy

