name: roadint
channels:
  - conda-forge
  - defaults
dependencies:
  - make
  - parallel=20210622
  - python=3.9
  - pip=21.1.*
  - gdal=3.3.*
  - geopandas=0.9.*
  - rasterio=1.2.*
  - libpq>=13.1
  - pip:
      - -r requirements.txt
variables:
  PGHOST: localhost
  PGUSER: postgres
  PGPASSWORD: postgres
  PGPORT: 5432
  PGDATABASE: roadintegrator