name: roadint
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=21.1.*
  - gdal=3.3.*
  - geopandas=0.9.*
  - rasterio=1.2.*
  - libpq>=13.1
  - pip:
      - bcdata==0.4.5
variables:
  PGHOST: localhost
  PGUSER: postgres
  PGPASSWORD: postgres
  PGPORT: 5435
  PGDATABASE: roadintegrator