name: roadintegrator
channels:
  - conda-forge
  - defaults
dependencies:
  - make
  - parallel
  - python
  - pip
  - gdal
  - geopandas
  - rasterio
  - libpq
  - pip:
      - bcdata
variables:
  DATABASE_URL: postgresql://postgres@localhost:5432/roadintegrator
