#!/bin/bash
set -euxo pipefail

# ----
# Download and tile BC WFS datasets
# ----

# get grid
python scripts/bc2pq.py \
  whse_basemapping.bcgs_20k_grid \
  --columns map_tile \
  --out_file s3://$OBJECTSTORE_BUCKET/whse_basemapping.bcgs_20k_grid.parquet

# everything else
python scripts/bc2pq.py \
  bcdata.json \
  --tile_dataset s3://$OBJECTSTORE_BUCKET/whse_basemapping.bcgs_20k_grid.parquet \
  --bounds 1117576,1003499,1392966,1232841
