#!/bin/bash
set -euxo pipefail

# ----
# For file based source data, download/tile/upload to objectstore
# ----

mkdir -p tmp

# DRA
curl ftp://ftp.geobc.gov.bc.ca/sections/outgoing/bmgs/DRA_Public/dgtl_road_atlas.gdb.zip \
  -o tmp/dgtl_road_atlas.gdb.zip

ogr2ogr \
  -f Parquet \
  tmp/whse_basemapping.transport_line.parquet \
  -select transport_line_id,structured_name_1,structured_name_1_id,capture_date,total_number_of_lanes,transport_line_structure_code,transport_line_type_code,transport_line_surface_code \
  -unsetFid \
  -dim XY \
  -where "TRANSPORT_LINE_SURFACE_CODE <> 'B'" \
  /vsizip/tmp/dgtl_road_atlas.gdb.zip \
  TRANSPORT_LINE

python scripts/intersect.py \
  tmp/whse_basemapping.transport_line.parquet \
  s3://$OBJECTSTORE_BUCKET/whse_basemapping.bcgs_20k_grid.parquet \
  s3://$OBJECTSTORE_BUCKET/whse_basemapping.transport_line.parquet

# dump dra code tables to csv and send to s3 vis awscli
ogr2ogr \
  -f CSV \
  tmp/whse_basemapping.transport_line_structure_code.csv \
  /vsizip/tmp/dgtl_road_atlas.gdb.zip \
  TRANSPORT_LINE_STRUCTURE_CODE

ogr2ogr \
  -f CSV \
  tmp/whse_basemapping.transport_line_type_code.csv \
  /vsizip/tmp/dgtl_road_atlas.gdb.zip \
  TRANSPORT_LINE_TYPE_CODE

ogr2ogr \
  -f CSV \
  tmp/whse_basemapping.transport_line_surface_code.csv \
  /vsizip/tmp/dgtl_road_atlas.gdb.zip \
  TRANSPORT_LINE_SURFACE_CODE

aws s3 cp tmp/whse_basemapping.transport_line_structure_code.csv s3://$OBJECTSTORE_BUCKET
aws s3 cp tmp/whse_basemapping.transport_line_type_code.csv s3://$OBJECTSTORE_BUCKET
aws s3 cp tmp/whse_basemapping.transport_line_surface_code.csv s3://$OBJECTSTORE_BUCKET

# Cariboo Roads
#curl ftp://ftp.geobc.gov.bc.ca/pub/outgoing/for_CE/Cariboo_Consolidated_Roads_20240304.zip \
#  -o tmp/Cariboo_Consolidated_Roads_20240304.gdb.zip
ogr2ogr \
  -f Parquet \
  -unsetFid \
  -dim XY \
  -select ccr_id,ccr_network_id,capture_date,structured_name_1,transport_line_type_code,transport_line_structure_code,transport_line_tenure_type_code,deactivation_date,private_flag,access_restricted_flag,access_restriction_type,ground_truth_required,desktop_ex_status \
  tmp/cariboo_consolidated_roads.parquet \
  /vsizip/tmp/Cariboo_Consolidated_Roads_20240304.gdb.zip \
  Cariboo_Consolidated_Roads

python scripts/intersect.py \
  tmp/cariboo_consolidated_roads.parquet \
  s3://$OBJECTSTORE_BUCKET/whse_basemapping.bcgs_20k_grid.parquet \
  s3://$OBJECTSTORE_BUCKET/cariboo_consolidated_roads.parquet

# cariboo road status
#curl ftp://ftp.geobc.gov.bc.ca/pub/outgoing/for_CE/Project_Tracking_20240304.zip \
#  -o tmp/Project_Tracking_20240304.gdb.zip

# create the cariboo cutter
python scripts/cariboo_cutter.py s3://$OBJECTSTORE_BUCKET/cariboo_cutter.parquet
