#!/bin/bash
set -euxo pipefail

# ----
# For file based source data, download/tile/upload to objectstore
# ----

mkdir -p tmp

# DRA
curl ftp://ftp.geobc.gov.bc.ca/sections/outgoing/bmgs/DRA_Public/dgtl_road_atlas.gdb.zip \
  -o tmp/dgtl_road_atlas.gdb.zip

ogr2ogr \
  -f Parquet \
  tmp/whse_basemapping.transport_line.parquet \
  -where "TRANSPORT_LINE_SURFACE_CODE <> 'B'" \
  /vsizip/tmp/dgtl_road_atlas.gdb.zip \
  TRANSPORT_LINE

python intersect.py \
  tmp/whse_basemapping.transport_line.parquet \
  s3://$OBJECTSTORE_BUCKET/whse_basemapping.bcgs_20k_grid.parquet \
  s3://$OBJECTSTORE_BUCKET/whse_basemapping.transport_line.parquet

# dump dra code tables to csv
ogr2ogr \
  -f CSV \
  s3://$OBJECTSTORE_BUCKET/whse_basemapping.transport_line_structure_code.csv \
  /vsizip/tmp/dgtl_road_atlas.gdb.zip \
  TRANSPORT_LINE_STRUCTURE_CODE

ogr2ogr \
  -f CSV \
  s3://$OBJECTSTORE_BUCKET/whse_basemapping.transport_line_type_code.csv \
  /vsizip/tmp/dgtl_road_atlas.gdb.zip \
  TRANSPORT_LINE_TYPE_CODE

ogr2ogr \
  -f CSV \
  s3://$OBJECTSTORE_BUCKET/whse_basemapping.transport_line_surface_code.csv \
  /vsizip/tmp/dgtl_road_atlas.gdb.zip \
  TRANSPORT_LINE_SURFACE_CODE

# Cariboo Roads
curl ftp://ftp.geobc.gov.bc.ca/pub/outgoing/for_CE/Cariboo_Consolidated_Roads_20240304.zip \
  -o tmp/Cariboo_Consolidated_Roads_20240304.gdb.zip
ogr2ogr \
  -f Parquet \
  tmp/cariboo_consolidated_roads.parquet \
  /vsizip/tmp/Cariboo_Consolidated_Roads_20240304.gdb.zip \
  Cariboo_Consolidated_Roads

python intersect.py \
  tmp/cariboo_consolidated_roads.parquet \
  s3://$OBJECTSTORE_BUCKET/whse_basemapping.bcgs_20k_grid.parquet \
  s3://$OBJECTSTORE_BUCKET/cariboo_consolidated_roads.parquet

rm -rf tmp
