#!/bin/bash
set -euxo pipefail

# ----
# Download file based datasets to local drive
# ----

mkdir -p tmp

# DRA
curl ftp://ftp.geobc.gov.bc.ca/sections/outgoing/bmgs/DRA_Public/dgtl_road_atlas.gdb.zip \
  -o tmp/dgtl_road_atlas.gdb.zip
ogr2ogr \
  -f Parquet \
  sources/whse_basemapping.transport_line.parquet \
  -where "TRANSPORT_LINE_SURFACE_CODE <> 'B'" \
  /vsizip/tmp/dgtl_road_atlas.gdb.zip \
  TRANSPORT_LINE

# dump dra code tables to csv
ogr2ogr \
  -f CSV \
  sources/whse_basemapping.transport_line_structure_code.csv \
  /vsizip/tmp/dgtl_road_atlas.gdb.zip \
  TRANSPORT_LINE_STRUCTURE_CODE

ogr2ogr \
  -f CSV \
  sources/whse_basemapping.transport_line_type_code.csv \
  /vsizip/tmp/dgtl_road_atlas.gdb.zip \
  TRANSPORT_LINE_TYPE_CODE

ogr2ogr \
  -f CSV \
  sources/whse_basemapping.transport_line_surface_code.csv \
  /vsizip/tmp/dgtl_road_atlas.gdb.zip \
  TRANSPORT_LINE_SURFACE_CODE


# Cariboo Roads
curl ftp://ftp.geobc.gov.bc.ca/pub/outgoing/for_CE/Cariboo_Consolidated_Roads_20240304.zip \
  -o tmp/Cariboo_Consolidated_Roads_20240304.gdb.zip
ogr2ogr \
  -f Parquet \
  sources/cariboo_consolidated_roads.parquet \
  /vsizip/tmp/Cariboo_Consolidated_Roads_20240304.gdb.zip \
  Cariboo_Consolidated_Roads

rm -rf tmp
