#!/bin/bash
set -euxo pipefail

# ----
# clean ften roads
# ----

PSQL="psql $DATABASE_URL -v ON_ERROR_STOP=1"

ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -lco GEOMETRY_NAME=geom \
  -overwrite \
  -nln whse_forest_tenure.ften_road_section_lines_svw \
  -nlt PROMOTE_TO_MULTI \
  /vsis3/$BUCKET/sources/whse_forest_tenure.ften_road_section_lines_svw.parquet \
  whse_forest_tenure.ften_road_section_lines_svw

$PSQL -c "DROP TABLE IF EXISTS ften_cleaned"

$PSQL -c "CREATE TABLE ften_cleaned (
  ften_active_id serial primary key,
  forest_file_id text,
  road_section_id text,
  file_status_code text,
  file_type_code text,
  file_type_description text,
  life_cycle_status_code text,
  award_date text,
  retirement_date text,
  client_number text,
  client_name text,
  map_label text,
  map_tile text,
  geom geometry(Linestring,3005)
);"

$PSQL -tXA \
  -c "SELECT DISTINCT map_tile
      FROM whse_forest_tenure.ften_road_section_lines_svw
      WHERE life_cycle_status_code = 'ACTIVE'
      ORDER BY map_tile" \
  | parallel --tag $PSQL -f sql/preprocess_ften.sql -v tile={1} -v status=ACTIVE

$PSQL -tXA \
  -c "SELECT DISTINCT map_tile
      FROM whse_forest_tenure.ften_road_section_lines_svw
      WHERE life_cycle_status_code = 'RETIRED'
      ORDER BY map_tile" \
  | parallel --tag $PSQL -f sql/preprocess_ften.sql -v tile={1} -v status=RETIRED

# dump to local file (required for indexing)
ogr2ogr \
  -f Parquet \
  /tmp/whse_forest_tenure.ften_road_section_lines_svw_cleaned.parquet \
  PG:$DATABASE_URL \
  -lco COMPRESSION=ZSTD \
  -lco COMPRESSION_LEVEL=15 \
  -lco SORT_BY_BBOX=YES \
  -sql "select * from ften_cleaned"

# upload
aws s3 cp /tmp/whse_forest_tenure.ften_road_section_lines_svw_cleaned.parquet \
  s3://$BUCKET/sources/whse_forest_tenure.ften_road_section_lines_svw_cleaned.parquet 