#!/bin/bash
set -euxo pipefail

# ----
# clean ften roads
# ----

PSQL="psql $DATABASE_URL -v ON_ERROR_STOP=1"

# ensure correct types by mirroring BCGW schema
bcdata bc2pg -e -c 1 whse_forest_tenure.ften_road_section_lines_svw
$PSQL -c "alter table whse_forest_tenure.ften_road_section_lines_svw add column map_tile text"

ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -nln whse_forest_tenure.ften_road_section_lines_svw_active \
  -append \
  -update \
  /vsis3/$OBJECTSTORE_BUCKET/whse_forest_tenure.ften_road_section_lines_svw.parquet \
  whse_forest_tenure.ften_road_section_lines_svw

$PSQL -c "DROP TABLE IF EXISTS ften_cleaned"

$PSQL -c "CREATE TABLE ften_cleaned (
  ften_active_id serial primary key,
  forest_file_id text,
  road_section_id text,
  file_status_code text,
  file_type_code text,
  file_type_description text,
  life_cycle_status_code text,
  award_date date,
  client_number text,
  client_name text,
  map_label text,
  map_tile text,
  geom geometry(Linestring,3005)
);"

$PSQL -tXA \
  -c "SELECT DISTINCT map_tile
      FROM whse_forest_tenure.ften_road_section_lines_svw
      ORDER BY map_tile" \
  | parallel --tag $PSQL -f sql/preprocess_ften.sql -v tile={1}

# dump to file
ogr2ogr \
  -f Parquet \
  /vsis3/$OBJECTSTORE_BUCKET/ften_cleaned.parquet \
  PG:$DATABASE_URL \
  -sql "select * from ften_cleaned"
