#!/bin/bash
set -euxo pipefail

# ----
# clean active ften roads
# ----

PSQL="psql $DATABASE_URL -v ON_ERROR_STOP=1"

ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -nln whse_forest_tenure.ften_road_section_lines_svw_active \
  -lco GEOMETRY_NAME=geom \
  -overwrite \
  -select map_label,map_tile \
  /vsis3/$OBJECTSTORE_BUCKET/whse_forest_tenure.ften_road_section_lines_svw_active.parquet \
  whse_forest_tenure.ften_road_section_lines_svw_active

$PSQL -c "DROP TABLE IF EXISTS ften_active"

$PSQL -c "CREATE TABLE ften_active (
  ften_active_id serial primary key,
  map_label character varying,
  map_tile character varying,
  geom geometry(Linestring,3005)
);"

$PSQL -tXA \
  -c "SELECT DISTINCT map_tile
      FROM whse_forest_tenure.ften_road_section_lines_svw_active
      ORDER BY map_tile" \
  | parallel --progress \
  $PSQL -f sql/preprocess_ften_active.sql -v tile={1}

$PSQL -c "CREATE INDEX on ften_active USING GIST (geom);"