#!/bin/bash
set -euxo pipefail

# ----
# convert OG permit right of ways (poly) to lines
# ----

PSQL="psql $DATABASE_URL -v ON_ERROR_STOP=1"

ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -append \
  --config OGR_TRUNCATE=YES \
  -nln whse_basemapping.bcgs_20k_grid \
  /vsis3/$BUCKET/sources/whse_basemapping.bcgs_20k_grid.parquet \
  whse_basemapping.bcgs_20k_grid

ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -nln whse_mineral_tenure.og_road_area_permit_sp \
  -lco GEOMETRY_NAME=geom \
  -overwrite \
  -select og_road_area_permit_id,map_tile \
  /vsis3/$BUCKET/sources/whse_mineral_tenure.og_road_area_permit_sp.parquet \
  whse_mineral_tenure.og_road_area_permit_sp

$PSQL -c "DROP TABLE IF EXISTS og_permits_row"

$PSQL -c "CREATE TABLE og_permits_row (
  og_permits_row_id serial primary key,
  map_tile character varying,
  geom geometry(Linestring, 3005)
)"

$PSQL -tXA \
-c "SELECT DISTINCT map_tile
    FROM whse_mineral_tenure.og_road_area_permit_sp
    ORDER BY map_tile" \
     | parallel --tag \
       $PSQL -f sql/roadpoly2line.sql \
       -v tile={1} \
       -v in_table=whse_mineral_tenure.og_road_area_permit_sp \
       -v out_table=og_permits_row

# dump to local file (required for indexing)
ogr2ogr \
  -f Parquet \
  /tmp/og_permits_row_cleaned.parquet \
  PG:$DATABASE_URL \
  -lco COMPRESSION=ZSTD \
  -lco COMPRESSION_LEVEL=15 \
  -lco SORT_BY_BBOX=YES \
  -sql "select * from og_permits_row"

# upload
aws s3 cp /tmp/og_permits_row_cleaned.parquet s3://$BUCKET/sources/og_permits_row_cleaned.parquet  