#!/bin/bash
set -euxo pipefail

# ----
# integrate the roads
# ----

tile=${1:-}
PSQL="psql $DATABASE_URL -v ON_ERROR_STOP=1"

# create initial output geometry table / source table
$PSQL -f sql/integratedroads_1.sql

# load dra to output
$PSQL -tXA \
  -c "INSERT INTO integratedroads_1 (
        transport_line_id,
        map_tile,
        geom
      )
      SELECT
        transport_line_id,
        map_tile,
        ST_MakeValid((st_dump(geom)).geom) as geom
      FROM whse_basemapping.transport_line
      WHERE map_tile like '$tile%'"

# load all other sources in descending order of priority
psql $DATABASE_URL -tXA \
-c "SELECT DISTINCT map_tile
    FROM ften_active
    WHERE map_tile like '$tile%'
    ORDER BY map_tile" \
    | parallel --tag \
      $PSQL -f sql/load_difference.sql -v tile={1} -v src_roads=ften_active -v pk=map_label

psql $DATABASE_URL -tXA \
-c "SELECT DISTINCT map_tile
    FROM ften_retired
    WHERE map_tile like '$tile%'
    ORDER BY map_tile" \
    | parallel --tag \
      $PSQL -f sql/load_difference.sql -v tile={1} -v src_roads=ften_retired -v pk=map_label

psql $DATABASE_URL -tXA \
-c "SELECT DISTINCT map_tile
    FROM results
    WHERE map_tile like '$tile%'
    ORDER BY map_tile" \
    | parallel --tag \
      $PSQL -f sql/load_difference.sql -v tile={1} -v src_roads=results -v pk=results_id

psql $DATABASE_URL -tXA \
-c "SELECT DISTINCT map_tile
    FROM whse_mineral_tenure.og_petrlm_dev_rds_pre06_pub_sp
    WHERE map_tile like '$tile%'
    ORDER BY map_tile" \
    | parallel --tag \
      $PSQL -f sql/load_difference.sql -v tile={1} -v src_roads=whse_mineral_tenure.og_petrlm_dev_rds_pre06_pub_sp -v pk=og_petrlm_dev_rd_pre06_pub_id

psql $DATABASE_URL -tXA \
-c "SELECT DISTINCT map_tile
    FROM whse_mineral_tenure.og_road_segment_permit_sp
    WHERE map_tile like '$tile%'
    ORDER BY map_tile" \
    | parallel --tag \
      $PSQL -f sql/load_difference.sql -v tile={1} -v src_roads=whse_mineral_tenure.og_road_segment_permit_sp -v pk=og_road_segment_permit_id

psql $DATABASE_URL -tXA \
-c "SELECT DISTINCT map_tile
    FROM og_permits_row
    WHERE map_tile like '$tile%'
    ORDER BY map_tile" \
    | parallel --tag \
      $PSQL -f sql/load_difference.sql -v tile={1} -v src_roads=og_permits_row -v pk=og_permits_row_id

# ----------
# for all features not present only in DRA, identify what other source roads
# intersect with the road's 7m buffer
# ----------
$PSQL -tXA -c "SELECT DISTINCT map_tile
               FROM integratedroads_1
               WHERE
                map_label is not null or
                results_id is not null or
                road_section_line_id is not null or
                og_petrlm_dev_rd_pre06_pub_id is not null or
                og_road_segment_permit_id is not null or
                og_permits_row_id is not null
               ORDER BY map_tile" \
  | parallel --tag $PSQL -f sql/load_sources.sql -v tile={1}

# with spatial processing complete, save disk by droping geometries from source tables
$PSQL -c "alter table whse_basemapping.transport_line drop column geom"
$PSQL -c "drop view ften_active; drop view ften_retired"
$PSQL -c "alter table whse_forest_tenure.ften_road_section_lines_svw drop column geom"
$PSQL -c "alter table results drop column geom"
$PSQL -c "alter table whse_forest_vegetation.rslt_forest_cover_inv_svw drop column geom"
$PSQL -c "alter table whse_mineral_tenure.og_petrlm_dev_rds_pre06_pub_sp drop column geom"
$PSQL -c "alter table whse_mineral_tenure.og_road_segment_permit_sp drop column geom"
$PSQL -c "alter table whse_mineral_tenure.og_road_area_permit_sp drop column geom"
$PSQL -c "alter table og_permits_row drop column geom"
$PSQL -c "VACUUM ANALYZE"


$PSQL -f sql/integratedroads_2.sql  # note all sources associated with an output geom
$PSQL -f sql/integratedroads.sql    # create output table

# remove file if it already exists
aws s3 rm s3://$BUCKET/integratedroads_$1.parquet

# dump to file
ogr2ogr \
  -f Parquet \
  -nlt LINESTRING \
  -nln integratedroads \
  -sql "SELECT * FROM integratedroads" \
  /vsis3/$BUCKET/integratedroads_$1.parquet \
  "PG:$DATABASE_URL"

#$PSQL --csv -f sql/summary.sql > summary.csv

# summarize road source by length and percentage in the output gpkg
#$PSQL --csv -c "WITH total AS \
#( \
#  SELECT SUM(ST_Length(geom)) AS total_length \
#  FROM integratedroads \
#) \
#SELECT \
#  bcgw_source, \
#  to_char(CURRENT_DATE, 'YYYY-MM-DD') as bcgw_extraction_date, \
#  ROUND((SUM(ST_Length(geom) / 1000)::numeric))  AS length_km, \
#  ROUND( \
#    (((SUM(ST_Length(geom)) / t.total_length)) * 100)::numeric, 1) as pct \
#FROM integratedroads, total t \
#GROUP BY bcgw_source, to_char(CURRENT_DATE, 'YYYY-MM-DD'), total_length \
#ORDER BY bcgw_source" > bcgw_source_summary.csv

#aws s3 cp bcgw_source_summary.csv s3://$BUCKET