#!/bin/bash
set -euxo pipefail

# ----
# integrate the roads
# ----

PSQL="psql $DATABASE_URL -v ON_ERROR_STOP=1"

# load sources to db

# DRA
ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -nln whse_basemapping.transport_line \
  -nlt PROMOTE_TO_MULTI \
  -lco GEOMETRY_NAME=geom \
  -overwrite \
  -where "map_tile_250 = '$1'" \
  /vsis3/$OBJECTSTORE_BUCKET/whse_basemapping.transport_line.parquet \
  whse_basemapping.transport_line
$PSQL -c "create index on whse_basemapping.transport_line (transport_line_id)"
$PSQL -c "create index on whse_basemapping.transport_line (map_tile)"

# ften
ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -nln whse_forest_tenure.ften_road_section_lines_svw \
  -lco GEOMETRY_NAME=geom \
  -overwrite \
  -where "map_tile_250 = '$1'" \
  /vsis3/$OBJECTSTORE_BUCKET/whse_forest_tenure.ften_road_section_lines_svw_cleaned.parquet \
  whse_forest_tenure.ften_road_section_lines_svw_cleaned
$PSQL -c "create index on whse_forest_tenure.ften_road_section_lines_svw (map_label)"
$PSQL -c "create index on whse_forest_tenure.ften_road_section_lines_svw (map_tile)"

# create views of retired/active ften roads
$PSQL -c "create view ften_active as (
  select
    row_number() over() as id,
    life_cycle_status_code,
    map_label,
    map_tile,
    geom
  from whse_forest_tenure.ften_road_section_lines_svw
  where life_cycle_status_code = 'ACTIVE'
)"

$PSQL -c "create view ften_retired as (
  select
    row_number() over() as id,
    life_cycle_status_code,
    map_label,
    map_tile,
    geom
  from whse_forest_tenure.ften_road_section_lines_svw
  where life_cycle_status_code = 'RETIRED'
)"

# results - both polys and lines are required
ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -nln results \
  -lco GEOMETRY_NAME=geom \
  -overwrite \
  -where "map_tile_250 = '$1'" \
  /vsis3/$OBJECTSTORE_BUCKET/results.parquet \
  results

ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -nln whse_forest_vegetation.rslt_forest_cover_inv_svw \
  -lco GEOMETRY_NAME=geom \
  -nlt PROMOTE_TO_MULTI \
  -overwrite \
  -where "map_tile_250 = '$1'" \
  /vsis3/$OBJECTSTORE_BUCKET/whse_forest_vegetation.rslt_forest_cover_inv_svw.parquet \
  whse_forest_vegetation.rslt_forest_cover_inv_svw
$PSQL -c "create index on whse_forest_vegetation.rslt_forest_cover_inv_svw (forest_cover_id)"
$PSQL -c "create index on whse_forest_vegetation.rslt_forest_cover_inv_svw (map_tile)"

# ogc linear features
ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -nln whse_mineral_tenure.og_petrlm_dev_rds_pre06_pub_sp \
  -lco GEOMETRY_NAME=geom \
  -overwrite \
  -where "map_tile_250 = '$1'" \
  /vsis3/$OBJECTSTORE_BUCKET/whse_mineral_tenure.og_petrlm_dev_rds_pre06_pub_sp.parquet \
  whse_mineral_tenure.og_petrlm_dev_rds_pre06_pub_sp
$PSQL -c "create index on whse_mineral_tenure.og_petrlm_dev_rds_pre06_pub_sp (og_petrlm_dev_rd_pre06_pub_id)"
$PSQL -c "create index on whse_mineral_tenure.og_petrlm_dev_rds_pre06_pub_sp (map_tile)"

ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -nln whse_mineral_tenure.og_road_segment_permit_sp \
  -lco GEOMETRY_NAME=geom \
  -overwrite \
  -where "map_tile_250 = '$1'" \
  /vsis3/$OBJECTSTORE_BUCKET/whse_mineral_tenure.og_road_segment_permit_sp.parquet \
  whse_mineral_tenure.og_road_segment_permit_sp
$PSQL -c "create index on whse_mineral_tenure.og_road_segment_permit_sp (og_road_segment_permit_id)"
$PSQL -c "create index on whse_mineral_tenure.og_road_segment_permit_sp (map_tile)"

ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -nln og_permits_row \
  -lco GEOMETRY_NAME=geom \
  -overwrite \
  -where "map_tile_250 = '$1'" \
  /vsis3/$OBJECTSTORE_BUCKET/og_permits_row.parquet \
  og_permits_row

# ogc polygons
ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -nln whse_mineral_tenure.og_road_area_permit_sp \
  -lco GEOMETRY_NAME=geom \
  -overwrite \
  -where "map_tile_250 = '$1'" \
  /vsis3/$OBJECTSTORE_BUCKET/whse_mineral_tenure.og_road_area_permit_sp.parquet \
  whse_mineral_tenure.og_road_area_permit_sp
$PSQL -c "create index on whse_mineral_tenure.og_road_area_permit_sp (og_road_area_permit_id)"
$PSQL -c "create index on whse_mineral_tenure.og_road_area_permit_sp (map_tile)"


# dra code tables
$PSQL -c "DROP TABLE IF EXISTS whse_basemapping.transport_line_structure_code;
DROP TABLE IF EXISTS whse_basemapping.transport_line_surface_code;
DROP TABLE IF EXISTS whse_basemapping.transport_line_type_code;

CREATE TABLE whse_basemapping.transport_line_structure_code (
        transport_line_structure_code character varying(1) PRIMARY KEY,
        description character varying(20) NOT NULL,
        create_integration_session_id integer NOT NULL,
        create_integration_date timestamp with time zone,
        modify_integration_session_id integer NOT NULL,
        modify_integration_date timestamp with time zone
);

CREATE TABLE whse_basemapping.transport_line_surface_code (
        transport_line_surface_code character varying(1) PRIMARY KEY,
        description character varying(20) NOT NULL,
        create_integration_session_id integer NOT NULL,
        create_integration_date timestamp with time zone,
        modify_integration_session_id integer NOT NULL,
        modify_integration_date timestamp with time zone
);

CREATE TABLE whse_basemapping.transport_line_type_code (
        transport_line_type_code character varying(3) PRIMARY KEY,
        description character varying(30) NOT NULL,
        demographic_ind character varying(1) NOT NULL,
        create_integration_session_id integer NOT NULL,
        create_integration_date timestamp with time zone,
        modify_integration_session_id integer NOT NULL,
        modify_integration_date timestamp with time zone,
        road_class character varying(12) NOT NULL
);"
ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -update \
  -append \
  -nln whse_basemapping.transport_line_type_code \
  /vsis3/$OBJECTSTORE_BUCKET/whse_basemapping.transport_line_type_code.csv \
  whse_basemapping.transport_line_type_code
ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -update \
  -append \
  -nln whse_basemapping.transport_line_surface_code \
  /vsis3/$OBJECTSTORE_BUCKET/whse_basemapping.transport_line_surface_code.csv \
  whse_basemapping.transport_line_surface_code
ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -update \
  -append \
  -nln whse_basemapping.transport_line_structure_code \
  /vsis3/$OBJECTSTORE_BUCKET/whse_basemapping.transport_line_structure_code.csv \
  whse_basemapping.transport_line_structure_code

# ----------
# process the roads
# ----------
# create initial output geometry table / source table
$PSQL -f sql/integratedroads_1.sql

# load dra to output
$PSQL -tXA \
  -c "INSERT INTO integratedroads_1 (
        transport_line_id,
        map_tile,
        geom
      )
      SELECT
        transport_line_id,
        map_tile,
        ST_MakeValid((st_dump(geom)).geom) as geom
      FROM whse_basemapping.transport_line"

# load all other sources in descending order of priority
psql $DATABASE_URL -tXA \
-c "SELECT DISTINCT map_tile
    FROM ften_active
    ORDER BY map_tile" \
    | parallel --tag \
      $PSQL -f sql/load_difference.sql -v tile={1} -v src_roads=ften_active -v pk=map_label

psql $DATABASE_URL -tXA \
-c "SELECT DISTINCT map_tile
    FROM ften_retired
    ORDER BY map_tile" \
    | parallel --tag \
      $PSQL -f sql/load_difference.sql -v tile={1} -v src_roads=ften_retired -v pk=map_label

psql $DATABASE_URL -tXA \
-c "SELECT DISTINCT map_tile
    FROM results
    ORDER BY map_tile" \
    | parallel --tag \
      $PSQL -f sql/load_difference.sql -v tile={1} -v src_roads=results -v pk=results_id

psql $DATABASE_URL -tXA \
-c "SELECT DISTINCT map_tile
    FROM whse_mineral_tenure.og_petrlm_dev_rds_pre06_pub_sp
    ORDER BY map_tile" \
    | parallel --tag \
      $PSQL -f sql/load_difference.sql -v tile={1} -v src_roads=whse_mineral_tenure.og_petrlm_dev_rds_pre06_pub_sp -v pk=og_petrlm_dev_rd_pre06_pub_id

psql $DATABASE_URL -tXA \
-c "SELECT DISTINCT map_tile
    FROM whse_mineral_tenure.og_road_segment_permit_sp
    ORDER BY map_tile" \
    | parallel --tag \
      $PSQL -f sql/load_difference.sql -v tile={1} -v src_roads=whse_mineral_tenure.og_road_segment_permit_sp -v pk=og_road_segment_permit_id

psql $DATABASE_URL -tXA \
-c "SELECT DISTINCT map_tile
    FROM og_permits_row
    ORDER BY map_tile" \
    | parallel --tag \
      $PSQL -f sql/load_difference.sql -v tile={1} -v src_roads=og_permits_row -v pk=og_permits_row_id

# ----------
# for all features not present only in DRA, identify what other source roads
# intersect with the road's 7m buffer
# ----------
$PSQL -tXA -c "SELECT DISTINCT map_tile
               FROM integratedroads_1
               WHERE
                map_label is not null or
                results_id is not null or
                road_section_line_id is not null or
                og_petrlm_dev_rd_pre06_pub_id is not null or
                og_road_segment_permit_id is not null or
                og_permits_row_id is not null
               ORDER BY map_tile" \
  | parallel --tag $PSQL -f sql/load_sources.sql -v tile={1}

# with spatial processing complete, save disk by droping geometries from source tables
$PSQL -c "alter table whse_basemapping.transport_line drop column geom"
$PSQL -c "drop view ften_active; drop view ften_retired"
$PSQL -c "alter table whse_forest_tenure.ften_road_section_lines_svw drop column geom"
$PSQL -c "alter table results drop column geom"
$PSQL -c "alter table whse_forest_vegetation.rslt_forest_cover_inv_svw drop column geom"
$PSQL -c "alter table whse_mineral_tenure.og_petrlm_dev_rds_pre06_pub_sp drop column geom"
$PSQL -c "alter table whse_mineral_tenure.og_road_segment_permit_sp drop column geom"
$PSQL -c "alter table whse_mineral_tenure.og_road_area_permit_sp drop column geom"
$PSQL -c "alter table og_permits_row drop column geom"
$PSQL -c "VACUUM ANALYZE"


$PSQL -f sql/integratedroads_2.sql  # note all sources associated with an output geom
$PSQL -f sql/integratedroads.sql    # create output table

# remove file if it already exists
aws s3 rm s3://$OBJECTSTORE_BUCKET/integratedroads_$1.parquet

# dump to file
ogr2ogr \
  -f Parquet \
  -nlt LINESTRING \
  -nln integratedroads \
  -sql "SELECT * FROM integratedroads" \
  /vsis3/$OBJECTSTORE_BUCKET/integratedroads_$1.parquet \
  "PG:$DATABASE_URL"

#$PSQL --csv -f sql/summary.sql > summary.csv

# summarize road source by length and percentage in the output gpkg
#$PSQL --csv -c "WITH total AS \
#( \
#  SELECT SUM(ST_Length(geom)) AS total_length \
#  FROM integratedroads \
#) \
#SELECT \
#  bcgw_source, \
#  to_char(CURRENT_DATE, 'YYYY-MM-DD') as bcgw_extraction_date, \
#  ROUND((SUM(ST_Length(geom) / 1000)::numeric))  AS length_km, \
#  ROUND( \
#    (((SUM(ST_Length(geom)) / t.total_length)) * 100)::numeric, 1) as pct \
#FROM integratedroads, total t \
#GROUP BY bcgw_source, to_char(CURRENT_DATE, 'YYYY-MM-DD'), total_length \
#ORDER BY bcgw_source" > bcgw_source_summary.csv

#aws s3 cp bcgw_source_summary.csv s3://$OBJECTSTORE_BUCKET