#!/bin/bash
set -euxo pipefail

# ----
# convert OG permit right of ways (poly) to lines
# ----

PSQL="psql $DATABASE_URL -v ON_ERROR_STOP=1"

ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -nln whse_mineral_tenure.og_road_area_permit_sp \
  -lco GEOMETRY_NAME=geom \
  -overwrite \
  -select og_road_area_permit_id,map_tile \
  /vsis3/$OBJECTSTORE_BUCKET/whse_mineral_tenure.og_road_area_permit_sp.parquet \
  whse_mineral_tenure.og_road_area_permit_sp

$PSQL -c "DROP TABLE IF EXISTS og_permits_row"

$PSQL -c "CREATE TABLE og_permits_row (
  og_permits_row_id serial primary key,
  map_tile character varying,
  geom geometry(Linestring, 3005)
)"

$PSQL -tXA \
-c "SELECT DISTINCT map_tile
    FROM whse_mineral_tenure.og_road_area_permit_sp r
    ORDER BY map_tile" \
     | parallel \
       $PSQL -f sql/roadpoly2line.sql \
       -v tile={1} \
       -v in_table=whse_mineral_tenure.og_road_area_permit_sp \
       -v out_table=og_permits_row > /dev/null

# dump to file
ogr2ogr \
  -f Parquet \
  /vsis3/$OBJECTSTORE_BUCKET/og_permits_row.parquet \
  PG:$DATABASE_URL \
  -sql "select * from og_permits_row"