#!/bin/bash
set -euxo pipefail

# get output parquet files
mkdir -p integratedroads
aws s3 cp s3://$OBJECTSTORE_BUCKET integratedroads --recursive --exclude "*" --include "integratedroads_*.parquet"

outfile=BC_CE_Integrated_Roads_$(date '+%Y')_$(date '+%Y%m%d').gdb
outlayer=integrated_roads_$(date '+%Y')

sources=BC_CE_Integrated_Roads_Sources_$(date '+%Y')_$(date '+%Y%m%d').gdb

rm -rf $outfile
rm -rf $outfile.zip

# dump to file
ogr2ogr   \
  -f OpenFileGDB \
  --config OPENFILEGDB_DEFAULT_STRING_WIDTH 255 \
  -nlt LINESTRING \
  -nln $outlayer \
  -sql "SELECT
   row_number() over() as \"INTEGRATED_ROADS_ID\",
   bcgw_source AS \"BCGW_SOURCE\",
   DATE('now') AS \"BCGW_EXTRACTION_DATE\",
   cef_road_priority_rank AS \"CEF_ROAD_PRIORITY_RANK\",
   cef_road_attr_src_list AS \"CEF_ROAD_ATTR_SRC_LIST\",
   map_tile AS \"MAP_TILE\",
   transport_line_id AS \"DRA_TRANSPORT_LINE_ID\",
   dra_structure AS \"DRA_ROAD_STRUCTURE\",
   dra_type AS \"DRA_ROAD_CLASS\",
   dra_surface AS \"DRA_ROAD_SURFACE\",
   dra_name_full AS \"DRA_ROAD_NAME_FULL\",
   dra_road_name_id AS \"DRA_ROAD_NAME_ID\",
   dra_data_capture_date AS \"DRA_DATA_CAPTURE_DATE\",
   dra_total_number_of_lanes AS \"DRA_NUMBER_OF_LANES\",
   ften_map_label AS \"FTEN_MAP_LABEL\",
   ften_forest_file_id AS \"FTEN_FOREST_FILE_ID\",
   ften_road_section_id AS \"FTEN_ROAD_SECTION_ID\",
   ften_file_status_code AS \"FTEN_FILE_STATUS_CODE\",
   ften_file_type_code AS \"FTEN_FILE_TYPE_CODE\",
   ften_file_type_description AS \"FTEN_FILE_TYPE_DESCRIPTION\",
   ften_life_cycle_status_code AS \"FTEN_LIFE_CYCLE_STATUS_CODE\",
   ften_award_date AS \"FTEN_AWARD_DATE\",
   ften_retirement_date AS \"FTEN_RETIREMENT_DATE\",
   ften_client_number AS \"FTEN_CLIENT_NUMBER\",
   ften_client_name AS \"FTEN_CLIENT_NAME\",
   results_forest_cover_id AS \"RESULTS_FOREST_COVER_ID\",
   results_opening_id AS \"RESULTS_OPENING_ID\",
   results_stocking_status_code AS \"RESULTS_STOCKING_STATUS_CODE\",
   results_stocking_type_code AS \"RESULTS_STOCKING_TYPE_CODE\",
   results_silv_polygon_number AS \"RESULTS_SILV_POLYGON_NUMBER\",
   results_reference_year AS \"RESULTS_REFERENCE_YEAR\",
   results_when_created AS \"RESULTS_WHEN_CREATED\",
   results_when_updated AS \"RESULTS_WHEN_UPDATED\",
   og_petrlm_dev_rd_pre06_pub_id AS \"OG_DEV_PRE06_OG_PETRLM_DEV_RD_PRE06_PUB_ID\",
   petrlm_development_road_type AS \"OG_DEV_PRE06_PETRLM_DEVELOPMENT_ROAD_TYPE\",
   application_received_date AS \"OG_DEV_PRE06_APPLICATION_RECEIVED_DATE\",
   proponent AS \"OG_DEV_PRE06_PROPONENT\",
   ogp_road_segment_permit_id AS \"OG_PERMITS_ROAD_SEGMENT_PERMIT_ID\",
   ogp_road_number AS \"OG_PERMITS_ROAD_NUMBER\",
   ogp_segment_number AS \"OG_PERMITS_SEGMENT_NUMBER\",
   ogp_road_type AS \"OG_PERMITS_ROAD_TYPE\",
   ogp_road_type_desc AS \"OG_PERMITS_ROAD_TYPE_DESC\",
   ogp_activity_approval_date AS \"OG_PERMITS_ACTIVITY_APPROVAL_DATE\",
   ogp_proponent AS \"OG_PERMITS_PROPONENT\",
   ogprow_og_road_area_permit_id AS \"OG_PERMITS_ROW_OG_ROAD_AREA_PERMIT_ID\",
   ogpermitsrow_road_number AS \"OG_PERMITS_ROW_ROAD_NUMBER\",
   ogp_row_road_segment AS \"OG_PERMITS_ROW_ROAD_SEGMENT\",
   ogp_row_land_stage_desc AS \"OG_PERMITS_ROW_LAND_STAGE_DESC\",
   ogp_row_land_stage_eff_date AS \"OG_PERMITS_ROW_LAND_STAGE_EFF_DATE\",
   ogp_row_construction_desc AS \"OG_PERMITS_ROW_CONSTRUCTION_DESC\",
   ogp_row_proponent AS \"OG_PERMITS_ROW_PROPONENT\",
   ogp_row_land_type AS \"OG_PERMITS_ROW_LAND_TYPE\",
   length_metres AS \"LENGTH_METRES\",
   geom
  FROM integratedroads" \
  -dialect SQLite \
  -lco CREATE_SHAPE_AREA_AND_LENGTH_FIELDS=YES \
  -mapfieldtype Integer64=Integer \
  $outfile \
  integratedroads

zip -r $outfile.zip $outfile
aws s3 cp $outfile.zip s3://$OBJECTSTORE_BUCKET

# archive source data
ogr2ogr   \
  -f OpenFileGDB \
  -nlt LINESTRING \
  -select TRANSPORT_LINE_ID,STRUCTURED_NAME_1,STRUCTURED_NAME_1_ID,CAPTURE_DATE,TOTAL_NUMBER_OF_LANES,TRANSPORT_LINE_STRUCTURE_CODE,TRANSPORT_LINE_TYPE_CODE,TRANSPORT_LINE_SURFACE_CODE,geometry \
  $sources \
  /vsis3/$OBJECTSTORE_BUCKET/whse_basemapping.transport_line.parquet \
  whse_basemapping.transport_line

ogr2ogr   \
  -f OpenFileGDB \
  -nlt LINESTRING \
  -update \
  -select forest_file_id,road_section_id,file_status_code,file_type_code,file_type_description,life_cycle_status_code,award_date,retirement_date,client_number,client_name,geometry \
  $sources \
  /vsis3/$OBJECTSTORE_BUCKET/whse_forest_tenure.ften_road_section_lines_svw.parquet \
  whse_forest_tenure.ften_road_section_lines_svw

ogr2ogr   \
  -f OpenFileGDB \
  -nlt POLYGON \
  -update \
  -select forest_cover_id,opening_id,stocking_status_code,stocking_type_code,silv_polygon_number,reference_year,forest_cover_when_created,forest_cover_when_updated,geometry \
  $sources \
  /vsis3/$OBJECTSTORE_BUCKET/whse_forest_vegetation.rslt_forest_cover_inv_svw.parquet \
  whse_forest_vegetation.rslt_forest_cover_inv_svw

ogr2ogr   \
  -f OpenFileGDB \
  -nlt LINESTRING \
  -update \
  -select og_petrlm_dev_rd_pre06_pub_id,ogc_file_number,application_received_date,petrlm_development_road_status,petrlm_development_road_num,petrlm_development_road_type,petrlm_development_road_name,proponent,source_data,feature_length_m,geometry \
  $sources \
  /vsis3/$OBJECTSTORE_BUCKET/whse_mineral_tenure.og_petrlm_dev_rds_pre06_pub_sp.parquet \
  whse_mineral_tenure.og_petrlm_dev_rds_pre06_pub_sp

ogr2ogr   \
  -f OpenFileGDB \
  -nlt POLYGON \
  -update \
  -select og_road_area_permit_id,land_id,road_number,road_segment,land_stage,land_stage_desc,land_stage_eff_date,application_determination_num,construction_code,construction_desc,legacy_ogc_file_number,proponent,authority_type,land_type,arch_permit_number,arch_requirement_code,arch_site_identified,data_source,feature_area_sqm,feature_length_m,geometry \
  $sources \
  /vsis3/$OBJECTSTORE_BUCKET/whse_mineral_tenure.og_road_area_permit_sp.parquet \
  whse_mineral_tenure.og_road_area_permit_sp

ogr2ogr   \
  -f OpenFileGDB \
  -nlt LINESTRING \
  -update \
  $sources \
  -select og_road_segment_permit_id,road_number,segment_number,road_width,road_type,road_type_desc,status,application_determination_num,activity_approval_date,legacy_ogc_file_number,proponent,authority_type,data_source,feature_length_m,geometry \
  /vsis3/$OBJECTSTORE_BUCKET/whse_mineral_tenure.og_road_segment_permit_sp.parquet \
  whse_mineral_tenure.og_road_segment_permit_sp

zip -r $sources.zip $sources
aws s3 cp $sources.zip s3://$OBJECTSTORE_BUCKET

# clean up
aws s3 rm s3://$OBJECTSTORE_BUCKET --recursive --exclude "*" --include "*.parquet"
aws s3 rm s3://$OBJECTSTORE_BUCKET --recursive --exclude "*" --include "*.csv"
