#!/bin/bash
set -euxo pipefail

# ----
# convert OG permit right of ways (poly) to lines
# ----

PSQL="psql $DATABASE_URL -v ON_ERROR_STOP=1"

# create output table
$PSQL -f sql/integratedroads.sql

# load DRA
ogr2ogr \
  -f PostgreSQL \
  "PG:$DATABASE_URL" \
  -nln whse_basemapping.transport_line \
  -lco GEOMETRY_NAME=geom \
  -overwrite \
  -select forest_cover_id,map_tile \
  tiled/whse_basemapping.transport_line.parquet \
  whse_basemapping.transport_line

# and load dra to output
$PSQL -tXA \
  -c "INSERT INTO integratedroads (
        transport_line_id,
        map_tile,
        geom
      )
      SELECT
        transport_line_id,
        map_tile,
        geom
      FROM whse_basemapping.transport_line"

# load all other sources
./integrateroads.sh

# index the foreign keys for faster joins back to source tables
$PSQL -c "CREATE INDEX ON integratedroads (transport_line_id)"
$PSQL -c "CREATE INDEX ON integratedroads (map_label)"
$PSQL -c "CREATE INDEX ON integratedroads (road_section_line_id)"
$PSQL -c "CREATE INDEX ON integratedroads (og_petrlm_dev_rd_pre06_pub_id)"
$PSQL -c "CREATE INDEX ON integratedroads (og_road_segment_permit_id)"