name: cariboo
run-name: ${{ github.actor }} Replace integrated roads with cariboo consolidated roads
on:
  workflow_dispatch:
  workflow_call:
env:
  DATABASE_URL: ${{ vars.DATABASE_URL }}
  AWS_ENDPOINT_URL: ${{ vars.AWS_ENDPOINT_URL }}
  AWS_S3_ENDPOINT: ${{ vars.AWS_S3_ENDPOINT  }}
  AWS_VIRTUAL_HOSTING: ${{ vars.AWS_VIRTUAL_HOSTING }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  OBJECTSTORE_BUCKET: ${{ secrets.OBJECTSTORE_BUCKET }}
  AWS_EC2_METADATA_DISABLED: ${{ vars.AWS_EC2_METADATA_DISABLED }}
  CPL_VSISTDIN_BUFFER_LIMIT: ${{ vars.CPL_VSISTDIN_BUFFER_LIMIT }}
jobs:
  integratedroads:
    runs-on: ubuntu-latest
    container: ghcr.io/bcgov/ce_integratedroads:main
    environment: production
    strategy:
      matrix:
        MAP_TILE: [092I,092N,092O,092P,093A,093B,093C,093F,093G,093H]
    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: cariboo
        run:  |
          jobs/00_setup_db
          jobs/07_cariboo ${{ matrix.MAP_TILE }}