name: ce-integratedroads
run-name: ${{ github.actor }} Full integrated roads workflow
on:
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  OBJECTSTORE_BUCKET: ${{ secrets.OBJECTSTORE_BUCKET }}
jobs:
  download:
    uses: ./.github/workflows/download.yaml
  preprocess:
    uses: ./.github/workflows/preprocess.yaml
    needs: download
  integrate:
    uses: ./.github/workflows/integrate.yaml
    needs: preprocess
  dump:
    uses: ./.github/workflows/dump.yaml
    needs: integrate