name: ce-integratedroads
run-name: ${{ github.actor }} Complete CE integrated roads workflow
on:
  workflow_dispatch:
jobs:
  download:
    uses: ./.github/workflows/download.yaml
  preprocess:
    uses: ./.github/workflows/preprocess.yaml
    needs: download
  integrate:
    uses: ./.github/workflows/integrate.yaml
    needs: preprocess
  dump:
    uses: ./.github/workflows/dump.yaml
    needs: integrate