name: ce-integratedroads
run-name: ${{ github.actor }} Integrated roads workflow
on:
  workflow_dispatch:
env:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
  AWS_ENDPOINT_URL: https://nrs.objectstore.gov.bc.ca
  AWS_S3_ENDPOINT: nrs.objectstore.gov.bc.ca
  AWS_VIRTUAL_HOSTING: FALSE
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  OBJECTSTORE_BUCKET: ${{ secrets.OBJECTSTORE_BUCKET }}
  AWS_EC2_METADATA_DISABLED: true
  CPL_VSISTDIN_BUFFER_LIMIT: -1
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: start
        run:  echo 'running integratedroads'
  download:
    uses: ./.github/workflows/download.yaml
  preprocess:
    uses: ./.github/workflows/preprocess.yaml
  integrate:
    uses: ./.github/workflows/integrate.yaml
  dump:
    uses: ./.github/workflows/dump.yaml