name: download
run-name: ${{ github.actor }} Download required datasets
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
jobs:
  download-wfs:
    runs-on: ubuntu-latest
    container: ghcr.io/bcgov/ce_integratedroads:main
    environment: ${{ inputs.env }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: WFS data - download/tile/dump
        run:  |
          jobs/01_download_wfs
  download-files:
    runs-on: ubuntu-latest
    container: ghcr.io/bcgov/ce_integratedroads:main
    environment: ${{ inputs.env }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: File data - download/tile/dump
        run:  |
          jobs/02_download_files