name: download
run-name: ${{ github.actor }} Download required datasets
on:
  workflow_dispatch:
  workflow_call:
env:
  DATABASE_URL: ${{ vars.DATABASE_URL }}
  CCR_URL: ${{ vars.CCR_URL }}
  CCR_TRACKING_URL: ${{ vars.CCR_URL }}
  AWS_ENDPOINT_URL: ${{ vars.AWS_ENDPOINT_URL }}
  AWS_S3_ENDPOINT: ${{ vars.AWS_S3_ENDPOINT  }}
  AWS_VIRTUAL_HOSTING: ${{ vars.AWS_VIRTUAL_HOSTING }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  OBJECTSTORE_BUCKET: ${{ secrets.OBJECTSTORE_BUCKET }}
  AWS_EC2_METADATA_DISABLED: ${{ vars.AWS_EC2_METADATA_DISABLED }}
  CPL_VSISTDIN_BUFFER_LIMIT: ${{ vars.CPL_VSISTDIN_BUFFER_LIMIT }}
jobs:
  download-wfs:
    runs-on: ubuntu-latest
    container: ghcr.io/bcgov/ce_integratedroads:main
    environment: production
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: WFS data - download/tile/dump
        run:  |
          jobs/01_download_wfs
  download-files:
    runs-on: ubuntu-latest
    container: ghcr.io/bcgov/ce_integratedroads:main
    environment: production
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: File data - download/tile/dump
        run:  |
          jobs/02_download_files