name: dump
run-name: ${{ github.actor }} Dump data to .gdb
on:
  workflow_dispatch:
  workflow_call:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  OBJECTSTORE_BUCKET: ${{ secrets.OBJECTSTORE_BUCKET }}
jobs:
  dump:
    runs-on: ubuntu-latest
    container: ghcr.io/bcgov/ce_integratedroads:main
    environment: production
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: dump
        run:
          jobs/07_dump