name: preprocess
run-name: ${{ github.actor }} Preprocess data
on:
  workflow_dispatch:
env:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
  AWS_ENDPOINT_URL: https://nrs.objectstore.gov.bc.ca
  AWS_S3_ENDPOINT: nrs.objectstore.gov.bc.ca
  AWS_VIRTUAL_HOSTING: FALSE
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  OBJECTSTORE_BUCKET: ${{ secrets.OBJECTSTORE_BUCKET }}
  AWS_EC2_METADATA_DISABLED: true
  CPL_VSISTDIN_BUFFER_LIMIT: -1
jobs:
  preprocess_ften_active:
    runs-on: ubuntu-latest
    container: ghcr.io/bcgov/ce_integratedroads:main
    steps:
      - name: test
        run:  ogrinfo /vsis3/$OBJECTSTORE_BUCKET/whse_forest_tenure.ften_road_section_lines_svw_active.parquet