name: preprocess
run-name: ${{ github.actor }} Preprocess required datasets
on:
  workflow_dispatch:
  workflow_call:
env:
  DATABASE_URL: ${{ vars.DATABASE_URL }}
  AWS_ENDPOINT_URL: ${{ vars.AWS_ENDPOINT_URL }}
  AWS_S3_ENDPOINT: ${{ vars.AWS_S3_ENDPOINT  }}
  AWS_VIRTUAL_HOSTING: ${{ vars.AWS_VIRTUAL_HOSTING }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET: ${{ secrets.BUCKET }}
  AWS_EC2_METADATA_DISABLED: ${{ vars.AWS_EC2_METADATA_DISABLED }}
  CPL_VSISTDIN_BUFFER_LIMIT: ${{ vars.CPL_VSISTDIN_BUFFER_LIMIT }}
jobs:
  preprocess-ften:
    runs-on: ubuntu-latest
    container: ghcr.io/bcgov/ce_integratedroads:main
    environment: production
    services:
      postgres:
        image: postgis/postgis:16-3.5
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Preprocess
        run:  |
          jobs/00_setup_db
          jobs/03_preprocess_ften
  preprocess-results:
    runs-on: ubuntu-latest
    container: ghcr.io/bcgov/ce_integratedroads:main
    environment: production
    services:
      postgres:
        image: postgis/postgis:16-3.5
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Preprocess
        run:  |
          jobs/00_setup_db
          jobs/04_preprocess_results
  preprocess-og-permits-row:
    runs-on: ubuntu-latest
    container: ghcr.io/bcgov/ce_integratedroads:main
    environment: production
    services:
      postgres:
        image: postgis/postgis:16-3.5
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Preprocess
        run:  |
          jobs/00_setup_db
          jobs/05_preprocess_og_permits_row